FROM node:22-alpine

WORKDIR /app

ARG APP_DIR

ENV NODE_ENV=production
ENV APP_DIR=${APP_DIR}

COPY protos ./protos

COPY ${APP_DIR}/package*.json ./${APP_DIR}/

WORKDIR /app/${APP_DIR}

RUN npm install

WORKDIR /app

COPY ${APP_DIR} ./${APP_DIR}

WORKDIR /app/${APP_DIR}

CMD ["npm", "start"]