services:

  db:
    image: postgres:15-alpine
    container_name: db_w05
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: student_db
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d student_db"]
      interval: 5s
      timeout: 30s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:4-management
    container_name: w05_rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: w06_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10

  course-nginx:
    image: nginx:1.27-alpine
    container_name: w06_course_nginx
    ports:
      - "15052:50052"
    volumes:
      - ./nginx/course-service.grpc.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis

volumes:
  db_data: