apiVersion: batch/v1
kind: Job
metadata:
  name: chat-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: chat-migrate
          image: w07/chat-service:dev
          imagePullPolicy: IfNotPresent
          command: ["npm", "run", "migrate"]
          env:
            - name: NODE_ENV
              value: development
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: w07-secrets
                  key: CHAT_DATABASE_URL
          envFrom:
            - configMapRef:
                name: w07-config
            - secretRef:
                name: w07-secrets
  backoffLimit: 1