apiVersion: batch/v1
kind: Job
metadata:
  name: student-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: student-migrate
          image: w07/student-service:dev
          imagePullPolicy: IfNotPresent
          command: ["npm", "run", "migrate"]
          env:
            - name: NODE_ENV
              value: development
            - name: DB_NAME
              value: student_db
          envFrom:
            - configMapRef:
                name: w07-config
            - secretRef:
                name: w07-secrets
  backoffLimit: 1